### ISSUE TITLE
cargo pkg version

### ISSUE THREAD

**Issue by hwchen** [matklad/xflags#11]
Just wondering if it would make sense to expose the cargo pkg version in help (using something like `env!("CARGO_PKG_VERSION");`)

In the interest of simplicity, I wouldn't even need/want to set the version manually.

And also in the interest of simplicity, I guess this would make the most sense if version was always-on in help, with no configuration in the macro.

The workaround would be to just hardcode the version into a doc comment.

I mention this because I hate keeping version numbers in sync within a project, but also find it really useful to see in the help.

**Comment by hwchen** [comment]
Ah, I see that this project is really meant for  "scripts" inside of a larger project. In which case having cargo version doesn't really make sense.

**Comment by matklad** [comment]
I do think we need a better story here. In particular, it should be possible to customize the help message, to add notes, version, etc. 

At the same time, I am not sure how to best do this. I’d rather let the user to assemble their own help message from pieces rather provide a configurable template.

**Comment by matklad** [comment]
I guess, we can have some kind of structured-help feature, which provides help as an array of structs, rather than a rendered string.
