### ISSUE TITLE
rust-analyzer fails to resolve invocations of `xflags::xflags!` 

### ISSUE THREAD

**Issue by thomcc** [matklad/xflags#14]
`xflags` is for the most part great (easy arg parsing without the compile time hit <3), but there are a few annoyances with using it. One of them is that rust-analyzer seems to be upset by it, producing errors like

```
unresolved macro `xflags::xflags!` rust-analyzer(unresolved-macro-call)
```

when the file containing the invocation happens to be open.

This, for the most part, isn't that big of a deal (just close the file, r-a shuts up, and everything works fine), but is an annoyance, and I've had to explain that this is what you should do to others on projects using xflags a couple times, so I figured I'd file a bug about it.

I assume the *real* solution is for rust-analyzer to get smarter, but... perhaps there's some workaround that xflags could to at least make this less annoying?

**Comment by lnicola** [comment]
This seems to happen because there's a `#[cfg(not(test))]`, see e.g. https://github.com/rust-analyzer/rust-analyzer/issues/9203.

**Comment by thomcc** [comment]
Adding `"rust-analyzer.cargo.unsetTest": ["core", "xflags-macros"]` the `whatever.code-workspace` or `.vscode/settings.json` seems to work around it.

This also, of course, works if you set it in your global settings. It might be nice to document, if there's no workaround that can be done inside this library.

**Comment by lnicola** [comment]
I tried to remove the https://github.com/matklad/xflags/blob/fd9ab2605dee4686160b9d22d6e76405027f5879/xflags-macros/src/lib.rs#L6 line and nothing broke, maybe we can do that?

**Comment by thomcc** [comment]
Submit a PR?
