### ISSUE TITLE
Improve UX on incorrect invocation

### ISSUE THREAD

**Issue by samoylovfp** [matklad/xflags#36]
I love the minimalistic approach of this crate but I find the experience of incorrect invocations lacking.

Currently the `parse_or_exit!` macro just prints `flag is required: 'arg'`
without mentioning `--help` flag and no way (that I found) to add information to that message.
IMO Ideally a CLI program will print an example of the invocation or at least hint that you can run it with `-h/--help`

Without diving into the code I think the most flexible path forward is to add a macro similar to `parse_or_exit` that returns something `Result`-like with a method `.unwrap_or_exit_with_msg("Try 'mytool --help' or 'mytool example.txt 123'")`
that adds a bit more context to the error message; Or add `default_message: ` clause to the macro DSL

**Comment by nilehmann** [comment]
Can you match on the result from `from_env` for your use case? This is what I have in my code to print the error message plus the help message when there's a bad invocation.

```rust
    let cmd = match Xtask::from_env() {
        Ok(cmd) => cmd,
        Err(err) => {
            if err.is_help() {
                println!("{err}");
                std::process::exit(0);
            } else {
                eprintln!("error: {err}\n");
                println!("{}", Xtask::HELP_);
                std::process::exit(2);
            }
        }
    };
```

**Comment by samoylovfp** [comment]
from env looks like exactly the method I was looking for, thanks!
