### ISSUE TITLE
struct field name generation rules

### ISSUE THREAD

**Issue by hwchen** [matklad/xflags#6]
This looked interesting, so I took it for a spin. This is for v0.2.1

Just from the behavior, it seems like
- long names are required (edit: I now see in the docs that it's required), and
- if a name is specified (not the short or long flag name) it doesn't have any effect on the struct field name.

So, for example, at https://github.com/matklad/xflags/blob/092d70de0777cee9502f3a062a2025258d52313b/examples/longer.rs#L34

The field name of the generated struct is from the long-flag-name only https://github.com/matklad/xflags/blob/092d70de0777cee9502f3a062a2025258d52313b/examples/longer.rs#L71

I was expecting that the struct name could any of name, long flag, short flag (in that order).

Let me know what you expect (and if I just missed something). I took a quick peek at the code, it looks like it'd fun to submit a PR

**Comment by matklad** [comment]
For --switches, --long name determins the name of struct's field, and (optional) value-name only affects the generated help

For positional arguments, (mandatory) value-name affects both the help and the fields name. 

In theory, in-place generation should answer such questions, but claryfing PR to the docs would be welcome!

**Comment by hwchen** [comment]
Ok, thanks for the clarification. I'll go back and take a look at the docs again.
